name: Build Binaries
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            .cache/pip
            .platformio/.cache
            venv
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run:
          |
          python -m venv venv
          source venv/bin/activate
          pip install --disable-pip-version-check --upgrade platformio

      - id: list
        name: List hardware
        run: |
          JSON=$(cat hardware.json | jq -c '.')
          echo matrix=${JSON} | tee -a $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            .cache/pip
            .platformio/.cache
            venv
          key: ${{ runner.os }}-pio

      - uses: montudor/action-zip@v1

      - name: Build artifacts
        run: |
          source venv/bin/activate
          platformio run --environment ${{ matrix.hardware }}
          set -x
          mv .pio/build/${{ matrix.hardware }}/*.bin MKS${{ matrix.assets_dir }}.bin
          if [ "${{ matrix.assets_dir }}" == "TFT32" ]; then
            mv "Copy to SD Card root directory to update/THEME_Unified Menu Material theme/TFT28" "${{ matrix.assets_dir }}"
          else
            mv "Copy to SD Card root directory to update/THEME_Unified Menu Material theme/${{ matrix.assets_dir }}" "."
          fi
          if [ "${{ matrix.custom_logo }}" != "" ]; then
            cp -a "Copy to SD Card root directory to update/THEME_Unified Menu Material theme/${{ matrix.custom_logo }}/bmp" \
              "${{ matrix.assets_dir }}"
          fi
          mv "Copy to SD Card root directory to update/config.ini" "."
          zip -mur ${{ matrix.hardware }}.zip MKS${{ matrix.assets_dir }}.bin ${{ matrix.assets_dir }} config.ini

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.hardware }}
          path: ${{ matrix.hardware }}.zip
          retention-days: 1

  release:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List files
        id: ziplist
        run: |
          echo 'files<<EOF' >> $GITHUB_OUTPUT
          ls -1 artifacts/**/*.zip | tee -a $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - id: create_release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: v${{ github.ref_name }}
          name: Release v${{ github.ref_name }}
          draft: false
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            ${{ steps.ziplist.outputs.files }}
