name: Build Prerelease
on:
  push:
    branches:
      - 'upstream'
  workflow_dispatch:

jobs:
  prerelease:
    uses: ./.github/workflows/buildTest.yml

  publish:
    needs: [prerelease]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - id: ziplist
        run: |
          echo 'files<<EOF' >> $GITHUB_OUTPUT
          ls -1 artifacts/**/*.zip | tee -a $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - id: create_release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: ${{ needs.prerelease.outputs.version }}
          name: Release ${{ needs.prerelease.outputs.version }}
          draft: false
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            ${{ steps.ziplist.outputs.files }}
