name: Build Test
on:
  pull_request:
    paths-ignore:
    - Bootloader/**
    - SDCard_install/**
    - images/**
    - readme/**
    - '**/*.md'

jobs:
  main:
    name: Build Test
    if: github.repository == 'bigtreetech/BIGTREETECH-TouchScreenFirmware'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio

      - name: Build Artillery TFT Controller V1.2
        run: platformio run --environment ARTILLERY_TFT_CONTROLLER_V1_2
